FROM alpine:3.15.0
LABEL maintainer="Rachid ABDELLAOUI" os="alpine" distro="stro"
ENV CONTAINER_USER="ABDELLAOUI_RACHID"
RUN adduser -S -D $CONTAINER_USER
CMD echo "hello-alpine, my name is $CONTAINER_USER and this is a container from my first image"
